email:
  sent_from : "1998amanahuja@gmail.com" 
  email_password : "amanisgreat"

  # [edit] enter receiver email details
  to : "amanahuja0657@gmail.com"

area_info:
# [edit] enter your district code or pincode
  __district_code : "247" 
  __pincode : "831001"
  
age_limit:
  age_limit : [18]
